kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
  extraPortMappings:
  - containerPort: 30950
    hostPort: 5552
- role: worker
  image: kindest/node:v1.30.0
networking:
  disableDefaultCNI: true
  apiServerPort: 5502
